/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/fila-espera/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Fila */
        get: operations["listar_fila_fila_espera__get"];
        put?: never;
        /** Criar Paciente */
        post: operations["criar_paciente_fila_espera__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fila-espera/busca-cpf/{cpf}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar Paciente Por Cpf */
        get: operations["buscar_paciente_por_cpf_fila_espera_busca_cpf__cpf__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fila-espera/minha-unidade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Fila Da Unidade */
        get: operations["listar_fila_da_unidade_fila_espera_minha_unidade_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fila-espera/{paciente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Paciente */
        get: operations["obter_paciente_fila_espera__paciente_id__get"];
        put?: never;
        post?: never;
        /** Remover Paciente */
        delete: operations["remover_paciente_fila_espera__paciente_id__delete"];
        options?: never;
        head?: never;
        /** Atualizar Paciente */
        patch: operations["atualizar_paciente_fila_espera__paciente_id__patch"];
        trace?: never;
    };
    "/fila-espera/{paciente_id}/regular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Regular Paciente */
        patch: operations["regular_paciente_fila_espera__paciente_id__regular_patch"];
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Autentica o usuário, retorna o Access Token no JSON e crava o Refresh Stateful no Banco e no Cookie.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Valida o cookie de Refresh, executa Rotação Atômica e devolve um novo Access Token.
         */
        post: operations["refresh_token_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Exclui o cookie e revoga a sessão no banco (se válida).
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estatisticas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter Resumo Gerencial
         * @description Retorna métricas agregadas da fila de espera do município para o Painel do Administrador.
         */
        get: operations["obter_resumo_gerencial_estatisticas__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/procedimentos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Procedimentos
         * @description Lista todos os procedimentos.
         *     O Front-end pode usar o parâmetro ?apenas_ativos=true para popular os menus suspensos.
         */
        get: operations["listar_procedimentos_procedimentos__get"];
        put?: never;
        /**
         * Criar Procedimento
         * @description Cria um novo procedimento (Apenas usuários autenticados).
         */
        post: operations["criar_procedimento_procedimentos__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/procedimentos/{procedimento_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Desabilitar Procedimento
         * @description Realiza o Soft Delete (desabilitação) do procedimento.
         *     Não apaga do banco para não quebrar o histórico da fila de espera.
         */
        delete: operations["desabilitar_procedimento_procedimentos__procedimento_id__delete"];
        options?: never;
        head?: never;
        /**
         * Atualizar Procedimento
         * @description Atualiza os dados de um procedimento existente.
         */
        patch: operations["atualizar_procedimento_procedimentos__procedimento_id__patch"];
        trace?: never;
    };
    "/unidades/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Unidades
         * @description Lista todas as unidades de saúde.
         *     O Front-end pode usar o parâmetro ?apenas_ativas=true para popular formulários.
         */
        get: operations["listar_unidades_unidades__get"];
        put?: never;
        /**
         * Criar Unidade
         * @description Cria uma nova unidade (Apenas usuários autenticados).
         */
        post: operations["criar_unidade_unidades__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unidades/{unidade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Desabilitar Unidade
         * @description Realiza o Soft Delete (desabilitação) da unidade.
         *     Não apaga do banco para manter a integridade dos históricos de pacientes e usuários.
         */
        delete: operations["desabilitar_unidade_unidades__unidade_id__delete"];
        options?: never;
        head?: never;
        /**
         * Atualizar Unidade
         * @description Atualiza os dados de uma unidade existente.
         */
        patch: operations["atualizar_unidade_unidades__unidade_id__patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BasePacienteResponse */
        BasePacienteResponse: {
            /**
             * Cpf
             * @description CPF do paciente
             */
            cpf: string;
            /**
             * Nome
             * @description Nome completo
             */
            nome: string;
            /**
             * Nascimento
             * @description Data de nascimento
             */
            nascimento?: string | null;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** EspecialidadeCount */
        EspecialidadeCount: {
            /** Procedimento */
            procedimento: string;
            /** Total */
            total: number;
        };
        /** FaixaEtariaCount */
        FaixaEtariaCount: {
            /** Faixa Etaria */
            faixa_etaria: string;
            /** Total */
            total: number;
        };
        /** FilaEsperaCreate */
        FilaEsperaCreate: {
            /**
             * Nome
             * @description Nome completo do paciente
             * @example João da Silva
             */
            nome: string;
            /**
             * Cpf Hash
             * @description Pode enviar o CPF com pontuação, somente números ou o hash SHA-256 já gerado.
             * @example 123.456.789-00
             * @example 12345678900
             */
            cpf_hash: string;
            /**
             * Nome Social
             * @description Nome social, se houver
             * @example João
             */
            nome_social?: string | null;
            /**
             * Nascimento
             * @description Data de nascimento
             * @example 1980-05-20
             */
            nascimento?: string | null;
            /**
             * Profissional Solicitante
             * @description Nome do médico ou enfermeiro solicitante
             * @example Dr. Carlos
             */
            profissional_solicitante: string;
            /**
             * Procedimento Id
             * @description ID do procedimento padronizado (Nova Estrutura)
             */
            procedimento_id?: string | null;
            /**
             * Unidade Origem Id
             * @description ID da unidade de saúde solicitante
             */
            unidade_origem_id?: string | null;
            /**
             * Tipo Procedimento
             * @description [LEGADO] Categoria do procedimento
             * @example CONSULTA
             * @example EXAME
             */
            tipo_procedimento?: string | null;
            /**
             * Procedimento Especifico
             * @description [LEGADO] Especialidade ou exame exato
             * @example CARDIOLOGIA
             */
            procedimento_especifico?: string | null;
            /** @description Classificação de prioridade do paciente */
            prioridade: components["schemas"]["PrioridadeFila"];
            /**
             * Tipo Fila
             * @description Natureza do procedimento (ex: PRIMEIRA_CONSULTA, RETORNO)
             * @default PRIMEIRA_CONSULTA
             * @example PRIMEIRA_CONSULTA
             * @example RETORNO
             */
            tipo_fila: string;
            /**
             * Data Solicitacao
             * @description Data real em que o pedido foi feito na UBS. Se omitido, assume o dia de hoje.
             * @example 2026-08-19
             */
            data_solicitacao?: string | null;
        };
        /** FilaEsperaPaginated */
        FilaEsperaPaginated: {
            /**
             * Total
             * @description Total absoluto de registros encontrados
             */
            total: number;
            /**
             * Items
             * @description Lista da página atual
             */
            items: components["schemas"]["FilaEsperaResponse"][];
        };
        /** FilaEsperaRegulacao */
        FilaEsperaRegulacao: {
            /** @description Novo status definido pelo regulador */
            status: components["schemas"]["StatusFila"];
            /** @description Risco clínico revisado */
            prioridade: components["schemas"]["PrioridadeFila"];
            /**
             * Data Agendamento
             * @description Obrigatório se AGENDADO
             * @example 2026-10-15
             */
            data_agendamento?: string | null;
            /**
             * Descricao Agendamento
             * @description Local de atendimento
             * @example AME ASSIS
             */
            descricao_agendamento?: string | null;
            /**
             * Justificativa Regulacao
             * @description Resumo da avaliação clínica
             * @example Paciente apresenta piora do quadro, prioridade elevada para PRIORITARIO.
             */
            justificativa_regulacao?: string | null;
        };
        /** FilaEsperaResponse */
        FilaEsperaResponse: {
            /**
             * Nome
             * @description Nome completo do paciente
             * @example João da Silva
             */
            nome: string;
            /**
             * Cpf Hash
             * @description Pode enviar o CPF com pontuação, somente números ou o hash SHA-256 já gerado.
             * @example 123.456.789-00
             * @example 12345678900
             */
            cpf_hash: string;
            /**
             * Nome Social
             * @description Nome social, se houver
             * @example João
             */
            nome_social?: string | null;
            /**
             * Nascimento
             * @description Data de nascimento
             * @example 1980-05-20
             */
            nascimento?: string | null;
            /**
             * Profissional Solicitante
             * @description Nome do médico ou enfermeiro solicitante
             * @example Dr. Carlos
             */
            profissional_solicitante: string;
            /**
             * Procedimento Id
             * @description ID do procedimento padronizado (Nova Estrutura)
             */
            procedimento_id?: string | null;
            /**
             * Unidade Origem Id
             * @description ID da unidade de saúde solicitante
             */
            unidade_origem_id?: string | null;
            /**
             * Tipo Procedimento
             * @description [LEGADO] Categoria do procedimento
             * @example CONSULTA
             * @example EXAME
             */
            tipo_procedimento?: string | null;
            /**
             * Procedimento Especifico
             * @description [LEGADO] Especialidade ou exame exato
             * @example CARDIOLOGIA
             */
            procedimento_especifico?: string | null;
            /** @description Classificação de prioridade do paciente */
            prioridade: components["schemas"]["PrioridadeFila"];
            /**
             * Tipo Fila
             * @description Natureza do procedimento (ex: PRIMEIRA_CONSULTA, RETORNO)
             * @default PRIMEIRA_CONSULTA
             * @example PRIMEIRA_CONSULTA
             * @example RETORNO
             */
            tipo_fila: string;
            /**
             * Data Solicitacao
             * Format: date
             * @description Data em que o pedido foi inserido
             */
            data_solicitacao: string;
            /**
             * Id
             * Format: uuid
             * @description ID único do registro
             */
            id: string;
            /** @description Status atual do paciente na fila */
            status: components["schemas"]["StatusFila"];
            /**
             * Data Agendamento
             * @description Data marcada (presente se status for AGENDADO)
             */
            data_agendamento?: string | null;
            /**
             * Descricao Agendamento
             * @description Local ou prestador onde o procedimento ocorrerá
             */
            descricao_agendamento?: string | null;
            /**
             * Created At
             * @description Data e hora do cadastro
             */
            created_at?: string | null;
            /**
             * Criado Por
             * @description ID do usuário que inseriu
             */
            criado_por?: string | null;
            /** @description Detalhes do procedimento associado a esta solicitação */
            procedimento?: components["schemas"]["ProcedimentoResponse"] | null;
        };
        /** FilaEsperaUpdate */
        FilaEsperaUpdate: {
            /** @description Altera o status do paciente */
            status?: components["schemas"]["StatusFila"] | null;
            /**
             * Data Agendamento
             * @description Obrigatório se status for mudado para AGENDADO. Formato: YYYY-MM-DD
             * @example 2026-10-15
             */
            data_agendamento?: string | null;
            /**
             * Descricao Agendamento
             * @description Local de agendamento (obrigatório se status for AGENDADO)
             * @example SANTA CASA DE PARAGUAÇU
             */
            descricao_agendamento?: string | null;
            /**
             * Justificativa Regulacao
             * @description Motivo técnico em caso de mudança de prioridade
             */
            justificativa_regulacao?: string | null;
            /** @description Altera a prioridade */
            prioridade?: components["schemas"]["PrioridadeFila"] | null;
            /**
             * Ordem Manual
             * @description Ordenação forçada manual
             */
            ordem_manual?: number | null;
            /**
             * Justificativa Cancelamento
             * @description Motivo se o status for mudado para CANCELADO
             */
            justificativa_cancelamento?: string | null;
        };
        /** GargaloEspecialidade */
        GargaloEspecialidade: {
            /** Procedimento */
            procedimento: string;
            /** Tempo Medio Dias */
            tempo_medio_dias: number;
            /** Total Aguardando */
            total_aguardando: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocalAgendamentoCount */
        LocalAgendamentoCount: {
            /** Local */
            local: string;
            /** Total */
            total: number;
        };
        /** PrioridadeCount */
        PrioridadeCount: {
            /** Prioridade */
            prioridade: string;
            /** Total */
            total: number;
        };
        /**
         * PrioridadeFila
         * @enum {string}
         */
        PrioridadeFila: "ELETIVO" | "PRIORITARIO";
        /** ProcedimentoCreate */
        ProcedimentoCreate: {
            /**
             * Nome
             * @description Nome padronizado do procedimento
             */
            nome: string;
            /** @description Tipo: CONSULTA, EXAME ou CIRURGIA */
            tipo: components["schemas"]["TipoProcedimento"];
            /**
             * Codigo Sigtap
             * @description Código unificado do SUS (opcional)
             */
            codigo_sigtap?: string | null;
            /**
             * Ativo
             * @default true
             */
            ativo: boolean;
        };
        /** ProcedimentoResponse */
        ProcedimentoResponse: {
            /**
             * Nome
             * @description Nome padronizado do procedimento
             */
            nome: string;
            /** @description Tipo: CONSULTA, EXAME ou CIRURGIA */
            tipo: components["schemas"]["TipoProcedimento"];
            /**
             * Codigo Sigtap
             * @description Código unificado do SUS (opcional)
             */
            codigo_sigtap?: string | null;
            /**
             * Ativo
             * @default true
             */
            ativo: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ProcedimentoUpdate */
        ProcedimentoUpdate: {
            /** Nome */
            nome?: string | null;
            tipo?: components["schemas"]["TipoProcedimento"] | null;
            /** Codigo Sigtap */
            codigo_sigtap?: string | null;
            /** Ativo */
            ativo?: boolean | null;
        };
        /** ResumoEstatisticas */
        ResumoEstatisticas: {
            /** Total Aguardando */
            total_aguardando: number;
            /** Tempo Medio Espera Dias */
            tempo_medio_espera_dias: number;
            /**
             * Total Nao Compareceu
             * @description Total de pacientes que faltaram ao agendamento
             */
            total_nao_compareceu: number;
            /** Por Especialidade */
            por_especialidade: components["schemas"]["EspecialidadeCount"][];
            /** Por Prioridade */
            por_prioridade: components["schemas"]["PrioridadeCount"][];
            /** Por Faixa Etaria */
            por_faixa_etaria: components["schemas"]["FaixaEtariaCount"][];
            /**
             * Por Local Agendamento
             * @description Ranking dos locais com mais agendamentos
             */
            por_local_agendamento: components["schemas"]["LocalAgendamentoCount"][];
            /**
             * Gargalos Por Especialidade
             * @description Especialidades com maior tempo de espera
             */
            gargalos_por_especialidade: components["schemas"]["GargaloEspecialidade"][];
        };
        /**
         * StatusFila
         * @enum {string}
         */
        StatusFila: "AGUARDANDO" | "AGENDADO" | "CANCELADO" | "REALIZADO" | "NÃO COMPARECEU";
        /**
         * TipoProcedimento
         * @enum {string}
         */
        TipoProcedimento: "CONSULTA" | "EXAME" | "CIRURGIA";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Usuario */
            usuario: {
                [key: string]: unknown;
            };
        };
        /**
         * UnidadeCreate
         * @description Schema para criação de uma nova unidade.
         */
        UnidadeCreate: {
            /**
             * Name
             * @description Nome da Unidade de Saúde (ex: CEM, Roseta IV)
             */
            name: string;
            /**
             * Active
             * @description Indica se a unidade está ativa para uso
             * @default true
             */
            active: boolean;
        };
        /**
         * UnidadeResponse
         * @description Schema de saída (Response) que será enviado ao Front-end.
         */
        UnidadeResponse: {
            /**
             * Name
             * @description Nome da Unidade de Saúde (ex: CEM, Roseta IV)
             */
            name: string;
            /**
             * Active
             * @description Indica se a unidade está ativa para uso
             * @default true
             */
            active: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * UnidadeUpdate
         * @description Schema para atualização (PATCH). Todos os campos são opcionais.
         */
        UnidadeUpdate: {
            /**
             * Name
             * @description Novo nome da unidade
             */
            name?: string | null;
            /**
             * Active
             * @description Status de ativação da unidade
             */
            active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_fila_fila_espera__get: {
        parameters: {
            query?: {
                /** @description Registros a pular (offset) */
                skip?: number;
                /** @description Limite de registros por página */
                limit?: number;
                /** @description Filtrar por status */
                status?: components["schemas"]["StatusFila"] | null;
                /** @description Filtrar por prioridade */
                prioridade?: components["schemas"]["PrioridadeFila"] | null;
                /** @description Filtrar por nome do paciente (busca parcial) */
                nome?: string | null;
                /** @description Filtrar a partir desta data de solicitação */
                data_inicio?: string | null;
                /** @description Filtrar até esta data de solicitação */
                data_fim?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilaEsperaPaginated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_paciente_fila_espera__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilaEsperaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilaEsperaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_paciente_por_cpf_fila_espera_busca_cpf__cpf__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cpf: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasePacienteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_fila_da_unidade_fila_espera_minha_unidade_get: {
        parameters: {
            query?: {
                /** @description Pular N registros (Paginação) */
                skip?: number;
                /** @description Limite de registros retornados */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilaEsperaResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_paciente_fila_espera__paciente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paciente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilaEsperaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remover_paciente_fila_espera__paciente_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paciente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_paciente_fila_espera__paciente_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paciente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilaEsperaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilaEsperaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regular_paciente_fila_espera__paciente_id__regular_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paciente_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilaEsperaRegulacao"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilaEsperaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_resumo_gerencial_estatisticas__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumoEstatisticas"];
                };
            };
        };
    };
    listar_procedimentos_procedimentos__get: {
        parameters: {
            query?: {
                apenas_ativos?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcedimentoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_procedimento_procedimentos__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcedimentoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcedimentoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desabilitar_procedimento_procedimentos__procedimento_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                procedimento_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_procedimento_procedimentos__procedimento_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                procedimento_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcedimentoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcedimentoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_unidades_unidades__get: {
        parameters: {
            query?: {
                apenas_ativas?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidadeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_unidade_unidades__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnidadeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidadeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desabilitar_unidade_unidades__unidade_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unidade_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_unidade_unidades__unidade_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unidade_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnidadeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidadeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
